### ISSUE TITLE
ACCESS_PASSWORD not working

### ISSUE THREAD

**Issue by Arcanum417** [alexcroox/R3-Web#12]
I have this defined in the config.php and I can still access any replay without giving password.
`define('ACCESS_PASSWORD', 'password');`

**Comment by alexcroox** [comment]
This feature isn't implemented yet

**Comment by Arcanum417** [comment]
I would then recommend putting a comment in config .

**Comment by alexcroox** [comment]
There is a lot of things that haven't been fully implemented so that's not realistic unfortunately.

There is a disclaimer in the README that this is heavy development and only in preview release form at the moment :)

![https://cl.ly/j1Gx/Screen%20Shot%202017-02-03%20at%2017.41.35.png](https://cl.ly/j1Gx/Screen%20Shot%202017-02-03%20at%2017.41.35.png)

I do appreciate the bug reports though.

**Comment by Arcanum417** [comment]
No problem, I noticed the DONT PUT IN PRODUCTION tag :D
I kinda got my instalation in good enough state so just ping me if you need something tested.
