### ISSUE TITLE
Long loading on 11 hour mission

### ISSUE THREAD

**Issue by Arcanum417** [alexcroox/R3-Web#8]
There is just a few missions but opening https://missionreport.417rct.org/ takes way too long, sometimes times out. Any advice ?

**Comment by Arcanum417** [comment]
Found my suspect. Got really horrible IO wait. Will try to fix it with my somewhat limited knowledge of Mysql and Linux

```
# Query_time: 47.412674  Lock_time: 0.286362 Rows_sent: 1  Rows_examined: 117239
SET timestamp=1486065094;
SELECT
                r.*,
                (SELECT added FROM events WHERE replayId = r.id ORDER BY added DESC LIMIT 1) as lastEventTime
            FROM
                replays r
            WHERE
                hidden = 0 AND
                (
                    r.lastEventMissionTime IS NULL OR
                    r.slug IS NULL OR
                    r.playerCount IS NULL OR
                    r.playerList IS NULL
                );
```

**Comment by alexcroox** [comment]
It looks like you had an 11 hour mission....

R3 is not optimised for such long running missions, when the first person visits the mission list, since new missions, it caches some data, but it does need to run through the events. Unfortunately for an 11 hour mission it probably really struggled to do so.

I do have some optimisations planned which might help but R3 definitely isn't designed for 11 hour missions.

**Comment by Arcanum417** [comment]
Sure thing, let me know. I can definitely provide testing for that optimisation. I have only one RAID 1 of sata drives on the server so I can feel every query.

**Comment by alexcroox** [comment]
I hope to address these issues soon, see here for more info https://github.com/alexcroox/R3-Web/issues/14

**Comment by Arcanum417** [comment]
Magic https://missionreport.417rct.org/5/gamemaster-417-2d
